#!/usr/bin/env python3
"""Fetch the latest @jgreerfilm posts into the local archive.

Reads a Behold.so JSON feed (env BEHOLD_FEED_URL). Carousels are split so each
slide can be chosen on its own. Everything lands in ig/originals/ and
ig/thumbs/, and photos.manifest.js is MERGED rather than replaced, so posts
that have aged out of the feed window stay available to pick from.

Selecting what actually appears on the site is a separate step:

    python3 tools/sync_instagram.py     # fetch and archive
    python3 tools/build_gallery.py      # apply photos.config.json
"""
import json
import os
import shutil
import ssl
import subprocess
import sys
import urllib.request

from PIL import Image, ImageOps

FEED = os.environ.get("BEHOLD_FEED_URL", "").strip()
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
THUMBS = os.path.join(ROOT, "ig", "thumbs")
ORIGINALS = os.path.join(ROOT, "ig", "originals")
MANIFEST = os.path.join(ROOT, "photos.manifest.js")
CATALOGUE = os.path.join(ROOT, "FEED.md")
THUMBPX, FULLPX = 440, 2000
UA = {"User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) "
                    "AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0 Safari/537.36"}


try:
    import certifi
    SSLCTX = ssl.create_default_context(cafile=certifi.where())
except ImportError:
    SSLCTX = ssl.create_default_context()


def fetch(url, binary=False):
    """urllib first; fall back to curl where Python has no CA bundle, which is
    the default state of a python.org install on macOS."""
    try:
        req = urllib.request.Request(url, headers=UA)
        with urllib.request.urlopen(req, timeout=90, context=SSLCTX) as r:
            raw = r.read()
    except (ssl.SSLError, urllib.error.URLError) as e:
        if not shutil.which("curl"):
            raise
        reason = getattr(e, "reason", e)
        if not isinstance(reason, ssl.SSLError) and "CERTIFICATE" not in str(reason).upper():
            raise
        raw = subprocess.run(
            ["curl", "-sSL", "--fail", "--max-time", "90",
             "-H", "User-Agent: " + UA["User-Agent"], url],
            check=True, capture_output=True).stdout
    return raw if binary else raw.decode("utf-8", "replace")


def best_url(obj):
    sizes = obj.get("sizes") or {}
    for k in ("full", "large", "medium", "small"):
        if sizes.get(k, {}).get("mediaUrl"):
            return sizes[k]["mediaUrl"]
    return obj.get("mediaUrl") or ""


def shortcode(permalink):
    parts = [p for p in (permalink or "").split("/") if p]
    return parts[-1] if parts else ""


def expand(doc):
    """One entry per image. A six slide carousel is six things to choose from."""
    posts = doc.get("posts") if isinstance(doc, dict) else doc
    items = []
    for p in posts or []:
        code0 = shortcode(p.get("permalink"))
        cap = (p.get("prunedCaption") or p.get("caption") or "").replace("\r", "")
        cap = cap.split("\n")[0][:70]
        common = {"permalink": p.get("permalink") or "", "caption": cap,
                  "ts": p.get("timestamp") or ""}
        kids = [c for c in (p.get("children") or [])
                if str(c.get("mediaType", "IMAGE")).upper() != "VIDEO"]
        if kids:
            for i, c in enumerate(kids, start=1):
                items.append(dict(common, code="%s_%d" % (code0, i), url=best_url(c)))
        elif str(p.get("mediaType", "")).upper() != "VIDEO":
            items.append(dict(common, code=code0, url=best_url(p)))
    return [i for i in items if i["code"] and i["url"]]


def pretty_date(ts):
    if not ts or len(ts) < 10:
        return ""
    import datetime
    try:
        d = datetime.datetime.fromisoformat(ts.replace("Z", "+00:00"))
    except ValueError:
        return ""
    return "%s %d, %d" % (d.strftime("%b"), d.day, d.year)


def load_manifest():
    if not os.path.exists(MANIFEST):
        return []
    s = open(MANIFEST, encoding="utf-8").read()
    try:
        return json.loads(s[s.index("["):s.rindex("]") + 1])
    except ValueError:
        return []


def save_manifest(man):
    man.sort(key=lambda p: p.get("ts") or "", reverse=True)
    with open(MANIFEST, "w", encoding="utf-8") as fh:
        fh.write("/* Written by tools/sync_instagram.py and tools/import_export.py.\n"
                 "   Every photo available to pick from. Loaded by picker.html. */\n")
        fh.write("window.PHOTO_MANIFEST = " +
                 json.dumps(man, ensure_ascii=False, indent=2) + ";\n")


def save_catalogue(man):
    lines = ["# Everything available to pick from", "",
             "Generated by the sync. Open `picker.html` to choose; it writes",
             "`photos.config.json`, which `tools/build_gallery.py` applies.", "",
             "| Code | Date | Caption |", "|---|---|---|"]
    for p in man:
        lines.append("| `%s` | %s | %s |" % (
            p["code"], p.get("date") or "?",
            (p.get("caption") or "").replace("|", "\\|") or "_no caption_"))
    open(CATALOGUE, "w", encoding="utf-8").write("\n".join(lines) + "\n")


def grab(item):
    """Download once; later runs reuse what is already on disk."""
    o = os.path.join(ORIGINALS, item["code"] + ".jpg")
    t = os.path.join(THUMBS, item["code"] + ".jpg")
    if os.path.exists(o) and os.path.exists(t):
        return True
    try:
        raw = fetch(item["url"], binary=True)
    except Exception as e:
        print("  could not fetch %s (%s)" % (item["code"], e))
        return False
    open(o, "wb").write(raw)
    im = ImageOps.exif_transpose(Image.open(o)).convert("RGB")
    full = im.copy()
    full.thumbnail((FULLPX, FULLPX), Image.LANCZOS)
    full.save(o, quality=86, optimize=True, progressive=True)
    th = im.copy()
    th.thumbnail((THUMBPX, THUMBPX), Image.LANCZOS)
    th.save(t, quality=78, optimize=True, progressive=True)
    return True


def main():
    if not FEED:
        print("BEHOLD_FEED_URL is not set. Nothing to do.")
        print("Add the feed URL as a repo variable named BEHOLD_FEED_URL.")
        return 0

    items = expand(json.loads(fetch(FEED)))
    if not items:
        print("Feed held no still images; archive left alone.")
        return 0
    print("Feed offered %d images." % len(items))

    os.makedirs(THUMBS, exist_ok=True)
    os.makedirs(ORIGINALS, exist_ok=True)

    man = load_manifest()
    by_code = {p["code"]: p for p in man}

    # a carousel that used to be archived under its bare shortcode is now
    # superseded by its numbered slides
    feed_codes = {i["code"] for i in items}
    bases = {c.split("_")[0] for c in feed_codes if "_" in c}
    for stale in [c for c in list(by_code) if c in bases]:
        del by_code[stale]
        print("  %s replaced by its carousel slides" % stale)

    added = 0
    for it in items:
        if not grab(it):
            continue
        if it["code"] not in by_code:
            added += 1
        by_code[it["code"]] = {
            "code": it["code"],
            "caption": it["caption"],
            "date": pretty_date(it["ts"]),
            "permalink": it["permalink"],
            "thumb": "ig/thumbs/%s.jpg" % it["code"],
            "full": "ig/originals/%s.jpg" % it["code"],
            "ts": it["ts"],
        }

    man = list(by_code.values())
    save_manifest(man)
    save_catalogue(man)
    print("\n%d new, %d total available to pick from." % (added, len(man)))
    print("Run tools/build_gallery.py to apply photos.config.json.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
