#!/usr/bin/env python3
"""Pull @jgreerfilm posts into this repo, honouring photos.config.json.

Reads a Behold.so JSON feed (env BEHOLD_FEED_URL), decides which posts to show,
downloads those stills into ig/, rewrites the POSTS array inside index.html
between the POSTS:START and POSTS:END markers, and writes FEED.md listing
everything the feed offered so you can pick from it.

photos.config.json
    mode    "auto"   newest first, minus anything in "hide", capped at "limit"
            "manual" exactly the posts in "order", in that order
    limit   how many to show in auto mode
    hide    post codes to skip in auto mode
    order   post codes, in the order you want them, for manual mode

A post code is the bit after /p/ in its URL:
    https://www.instagram.com/p/DceQvfAmdCo/  ->  DceQvfAmdCo
"""
import datetime
import json
import os
import re
import sys
import urllib.request

from PIL import Image, ImageOps

FEED = os.environ.get("BEHOLD_FEED_URL", "").strip()
MAXPX = 2000
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
IGDIR = os.path.join(ROOT, "ig")
PAGE = os.path.join(ROOT, "index.html")
CONFIG = os.path.join(ROOT, "photos.config.json")
CATALOGUE = os.path.join(ROOT, "FEED.md")
UA = {"User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) "
                    "AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0 Safari/537.36"}


def fetch(url, binary=False):
    req = urllib.request.Request(url, headers=UA)
    with urllib.request.urlopen(req, timeout=90) as r:
        raw = r.read()
    return raw if binary else raw.decode("utf-8", "replace")


def load_config():
    cfg = {"mode": "auto", "limit": 12, "hide": [], "order": []}
    if os.path.exists(CONFIG):
        try:
            with open(CONFIG, encoding="utf-8") as fh:
                cfg.update({k: v for k, v in json.load(fh).items()
                            if not k.startswith("_")})
        except Exception as e:
            print("photos.config.json could not be read (%s); using defaults." % e)
    cfg["hide"] = [str(x).strip() for x in cfg.get("hide") or []]
    cfg["order"] = [str(x).strip() for x in cfg.get("order") or []]
    try:
        cfg["limit"] = max(1, int(cfg.get("limit") or 12))
    except (TypeError, ValueError):
        cfg["limit"] = 12
    return cfg


def normalise(doc):
    """Behold returns {posts:[...]}; some feeds return a bare list."""
    items = doc if isinstance(doc, list) else (
        doc.get("posts") or doc.get("media") or doc.get("data") or [])
    out = []
    for m in items:
        if str(m.get("mediaType", "")).upper() == "VIDEO":
            continue
        sizes = m.get("sizes") or {}
        best = sizes.get("full") or sizes.get("large") or sizes.get("medium") or {}
        url = best.get("mediaUrl") or m.get("mediaUrl") or m.get("media_url")
        if not url:
            continue
        link = m.get("permalink", "")
        code = re.search(r"/p/([^/?]+)", link)
        caption = (m.get("caption") or "").strip().replace("\r", "")
        out.append({
            "url": url,
            "permalink": link,
            "code": code.group(1) if code else "",
            "caption": caption.split("\n")[0][:70],
            "ts": m.get("timestamp") or "",
        })
    return out


def choose(found, cfg):
    """Apply photos.config.json to the posts the feed gave us."""
    by_code = {p["code"]: p for p in found if p["code"]}
    if cfg["mode"] == "manual":
        picked, missing = [], []
        for code in cfg["order"]:
            if code in by_code:
                picked.append(by_code[code])
            else:
                missing.append(code)
        if missing:
            print("  not in the feed, skipped: %s" % ", ".join(missing))
        if not picked:
            print("  manual mode but nothing in \"order\" matched; falling back to auto.")
        else:
            return picked
    hidden = set(cfg["hide"])
    kept = [p for p in found if p["code"] not in hidden]
    if hidden:
        print("  hidden by config: %d" % (len(found) - len(kept)))
    return kept[:cfg["limit"]]


def pretty_date(ts):
    if not ts:
        return ""
    try:
        d = datetime.datetime.fromisoformat(ts.replace("Z", "+00:00"))
    except ValueError:
        return ""
    return "%s %d, %d" % (d.strftime("%b"), d.day, d.year)


def write_catalogue(found, shown_codes, cfg):
    lines = [
        "# Every post in the feed",
        "",
        "Generated by `tools/sync_instagram.py`. Edit **photos.config.json** to change",
        "what appears on the site, then run the Sync Instagram action.",
        "",
        "- `mode` is currently **%s**, `limit` **%d**" % (cfg["mode"], cfg["limit"]),
        "- To drop one photo: add its code to `hide`",
        "- To choose exactly which photos and in what order: set `mode` to `manual`",
        "  and list codes in `order`",
        "",
        "| On the site | Code | Date | Caption |",
        "|---|---|---|---|",
    ]
    for p in found:
        lines.append("| %s | `%s` | %s | %s |" % (
            "yes" if p["code"] in shown_codes else "no",
            p["code"], pretty_date(p["ts"]) or "?",
            (p["caption"] or "").replace("|", "\\|") or "_no caption_"))
    lines.append("")
    with open(CATALOGUE, "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines))


def js(s):
    return json.dumps(s, ensure_ascii=False)


def main():
    cfg = load_config()
    if not FEED:
        print("BEHOLD_FEED_URL is not set. Nothing to do.")
        print("Create a free feed at behold.so, then add the URL as a repo "
              "variable named BEHOLD_FEED_URL.")
        return 0

    found = normalise(json.loads(fetch(FEED)))
    if not found:
        print("Feed returned no still images; leaving the site untouched.")
        return 0
    print("Feed offered %d posts. Mode: %s." % (len(found), cfg["mode"]))

    posts = choose(found, cfg)
    if not posts:
        print("Config selected nothing; leaving the site untouched.")
        return 0

    os.makedirs(IGDIR, exist_ok=True)
    rows, keep, shown = [], set(), set()
    for n, p in enumerate(posts, start=1):
        name = "%02d.jpg" % n
        path = os.path.join(IGDIR, name)
        try:
            raw = fetch(p["url"], binary=True)
        except Exception as e:                      # one bad URL must not kill the run
            print("  skip %s (%s)" % (name, e))
            continue
        with open(path, "wb") as fh:
            fh.write(raw)
        im = ImageOps.exif_transpose(Image.open(path)).convert("RGB")
        im.thumbnail((MAXPX, MAXPX), Image.LANCZOS)
        im.save(path, quality=85, optimize=True, progressive=True)
        keep.add(name)
        shown.add(p["code"])
        rows.append('    {f:%s, w:%d,h:%d, t:%s, d:%s, p:%s}' % (
            js(name), im.width, im.height,
            js(p["caption"] or "Untitled"), js(pretty_date(p["ts"])), js(p["code"])))
        print("  %s  %dx%d  %s" % (name, im.width, im.height, p["caption"][:40]))

    write_catalogue(found, shown, cfg)

    if not rows:
        print("Nothing downloaded; leaving the site untouched.")
        return 0

    for stale in os.listdir(IGDIR):
        if stale.endswith(".jpg") and stale not in keep:
            os.remove(os.path.join(IGDIR, stale))
            print("  removed stale %s" % stale)

    page = open(PAGE, encoding="utf-8").read()
    block = ("  /* POSTS:START -- rewritten by tools/sync_instagram.py, do not hand edit */\n"
             "  var POSTS = [\n" + ",\n".join(rows) + "\n  ];\n"
             "  /* POSTS:END */")
    new, count = re.subn(
        r"  /\* POSTS:START.*?/\* POSTS:END \*/", block, page,
        count=1, flags=re.S)
    if not count:
        print("ERROR: POSTS markers not found in index.html", file=sys.stderr)
        return 1
    if new != page:
        open(PAGE, "w", encoding="utf-8").write(new)
        print("index.html updated with %d posts." % len(rows))
    else:
        print("Already up to date.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
